SURGERIES = [
    {"id": "surg1", "name": "Appendectomy", "description": "Surgical removal of the appendix, typically for appendicitis", "recovery_days": 14, "cost_min": 40000, "cost_max": 80000, "specialist_slug": "general-surgery", "image": "https://www.medibuddy.in/assets/icons/surgery/appendectomy.svg"},
    {"id": "surg2", "name": "Knee Replacement", "description": "Total or partial knee joint replacement for severe arthritis", "recovery_days": 90, "cost_min": 150000, "cost_max": 350000, "specialist_slug": "orthopedics", "image": "https://www.medibuddy.in/assets/icons/surgery/knee-replacement.svg"},
    {"id": "surg3", "name": "Cataract Surgery", "description": "Removal of clouded lens and replacement with artificial lens", "recovery_days": 7, "cost_min": 25000, "cost_max": 60000, "specialist_slug": "neurosurgeon", "image": "https://www.medibuddy.in/assets/icons/surgery/cataract.svg"},
    {"id": "surg4", "name": "Gallbladder Removal (Cholecystectomy)", "description": "Laparoscopic removal of gallbladder for gallstones", "recovery_days": 14, "cost_min": 50000, "cost_max": 100000, "specialist_slug": "general-surgery", "image": "https://www.medibuddy.in/assets/icons/surgery/gallbladder.svg"},
    {"id": "surg5", "name": "Hernia Repair", "description": "Surgical repair of abdominal wall hernias", "recovery_days": 21, "cost_min": 45000, "cost_max": 90000, "specialist_slug": "general-surgery", "image": "https://www.medibuddy.in/assets/icons/surgery/hernia.svg"},
    {"id": "surg6", "name": "Hip Replacement", "description": "Replacement of damaged hip joint with artificial prosthesis", "recovery_days": 90, "cost_min": 200000, "cost_max": 400000, "specialist_slug": "orthopedics", "image": "https://www.medibuddy.in/assets/icons/surgery/hip-replacement.svg"},
    {"id": "surg7", "name": "Coronary Bypass (CABG)", "description": "Heart bypass surgery to restore blood flow to heart muscles", "recovery_days": 60, "cost_min": 250000, "cost_max": 500000, "specialist_slug": "cardiologist", "image": "https://www.medibuddy.in/assets/icons/surgery/cabg.svg"},
    {"id": "surg8", "name": "Cesarean Section (C-Section)", "description": "Surgical delivery of baby through abdominal incision", "recovery_days": 42, "cost_min": 50000, "cost_max": 150000, "specialist_slug": "gynecologist", "image": "https://www.medibuddy.in/assets/icons/surgery/c-section.svg"},
    {"id": "surg9", "name": "Tonsillectomy", "description": "Surgical removal of tonsils for recurrent infections", "recovery_days": 14, "cost_min": 20000, "cost_max": 50000, "specialist_slug": "ent", "image": "https://www.medibuddy.in/assets/icons/surgery/tonsillectomy.svg"},
    {"id": "surg10", "name": "Spinal Fusion", "description": "Fusing two or more vertebrae to treat spinal instability", "recovery_days": 120, "cost_min": 300000, "cost_max": 600000, "specialist_slug": "neurosurgeon", "image": "https://www.medibuddy.in/assets/icons/surgery/spinal-fusion.svg"},
]
